# Generated by Django 3.0.2 on 2020-02-04 16:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('test_app', '0007_auto_20200204_1330'),
        ('passing_test', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useranswers',
            name='question',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='test_app.Questions', unique=True),
        ),
    ]
