# Generated by Django 3.0.2 on 2020-01-26 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='questions',
            name='answers_amount',
            field=models.IntegerField(default=4),
        ),
        migrations.AddField(
            model_name='questions',
            name='one_correct_answer',
            field=models.BooleanField(default=True),
        ),
    ]
