# Generated by Django 3.0.2 on 2020-01-27 13:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('test_app', '0002_auto_20200126_1811'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestQuestionUnion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='test_app.Questions')),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='test_app.TestQuiz')),
            ],
        ),
    ]
