# Generated by Django 3.0.2 on 2020-01-28 15:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('test_app', '0003_testquestionunion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testquestionunion',
            name='question',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='test_app.Questions'),
        ),
        migrations.AlterField(
            model_name='testquestionunion',
            name='test',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='test_app.TestQuiz'),
        ),
    ]
