# Generated by Django 3.0.2 on 2020-01-28 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_app', '0004_auto_20200128_1544'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answeroption',
            name='is_correct',
            field=models.BooleanField(default=False),
        ),
    ]
