# Generated by Django 3.0.2 on 2020-01-31 13:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('test_app', '0005_auto_20200128_1547'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testquestionunion',
            name='test',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='test_app.TestQuiz'),
        ),
    ]
