# Generated by Django 3.0.2 on 2020-02-04 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_app', '0006_auto_20200131_1306'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questions',
            name='question_text',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
