# Generated by Django 3.0.2 on 2020-01-22 19:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_login_reg', '0002_auto_20200122_1930'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='last_login',
        ),
        migrations.RemoveField(
            model_name='user',
            name='password',
        ),
    ]
